name: pokemon_app_wisemen
description: Test sollicitatie app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  pokemon_api:
    path: packages/pokemon_api
  flutter_bloc: ^8.0.1
  carousel_slider: ^4.1.1
  photo_view: ^0.14.0
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/playstore.png'
  image_path_ios: 'assets/appstore.png'

